In [1]:
import os
import glob
import pandas as pd
import numpy as np

# Table 1: Average UCI ranks

In [2]:
df = pd.read_csv("../results/all_aggregated.csv")

uci_methods = ["deterministic", "normal", "mixednormal", "sample"]
uci = df[(df["experiment"] == "UCI") & (df["method"].isin(uci_methods))][
    ["dataset", "method", "RMSETest_mean", "CRPSTest_mean"]
]

baseline = df[df["experiment"] == "crps_ensemble"][
    ["dataset", "method", "RMSETest_mean", "CRPSTest_mean"]
].copy()
uci_datasets = uci["dataset"].unique()
baseline = baseline[baseline["dataset"].isin(uci_datasets)]

table = pd.concat([uci, baseline], ignore_index=True)
table

                       dataset         method  RMSETest_mean  CRPSTest_mean
0                     concrete  deterministic       4.822526       2.591387
1                     concrete    mixednormal       4.741911       2.425323
2                     concrete         normal       4.786152       2.470271
3                     concrete         sample       4.825328       2.492164
4                       energy  deterministic       0.453455       0.289633
5                       energy    mixednormal       0.444514       0.241185
6                       energy         normal       0.453167       0.244400
7                       energy         sample       0.456294       0.247091
8                       kin8nm  deterministic       0.069107       0.039344
9                       kin8nm    mixednormal       0.068896       0.038194
10                      kin8nm         normal       0.068832       0.038112
11                      kin8nm         sample       0.069002       0.038259
12      naval-propulsion-plant  deterministic       0.000135       0.000080
13      naval-propulsion-plant    mixednormal       0.000123       0.000054
14      naval-propulsion-plant         normal       0.000124       0.000055
15      naval-propulsion-plant         sample       0.000124       0.000054
16                 power-plant  deterministic       3.856285       2.040349
17                 power-plant    mixednormal       3.593167       1.805458
18                 power-plant         normal       3.636255       1.838473
19                 power-plant         sample       3.776304       1.934145
20  protein-tertiary-structure  deterministic       3.763847       1.713487
21  protein-tertiary-structure    mixednormal       3.716138       1.653851
22  protein-tertiary-structure         normal       3.712632       1.660162
23  protein-tertiary-structure         sample       3.764736       1.693720
24            wine-quality-red  deterministic       0.662035       0.331232
25            wine-quality-red    mixednormal       0.677785       0.353366
26            wine-quality-red         normal       0.653729       0.329430
27            wine-quality-red         sample       0.660278       0.331364
28                       yacht  deterministic       0.939685       0.408734
29                       yacht    mixednormal       0.945362       0.358783
30                       yacht         normal       0.906205       0.347457
31                       yacht         sample       0.992245       0.370034
32                    concrete  crps_ensemble       4.600633       2.491515
33                      energy  crps_ensemble       0.502862       0.283139
34                      kin8nm  crps_ensemble       0.079461       0.047035
35      naval-propulsion-plant  crps_ensemble       0.000727       0.000417
36                 power-plant  crps_ensemble       3.625245       1.917772
37  protein-tertiary-structure  crps_ensemble       3.799449       1.931882
38            wine-quality-red  crps_ensemble       0.669688       0.386747
39                       yacht  crps_ensemble       1.033802       0.484462

In [3]:
# Rank methods within each dataset (lower metric = better -> rank 1)
rmse_ranks = (
    table.pivot(index="dataset", columns="method", values="RMSETest_mean")
    .rank(axis=1, method="min")
)
crps_ranks = (
    table.pivot(index="dataset", columns="method", values="CRPSTest_mean")
    .rank(axis=1, method="min")
)

avg_ranks = pd.DataFrame({
    "RMSE_avg_rank": rmse_ranks.mean(axis=0),
    "CRPS_avg_rank": crps_ranks.mean(axis=0),
})
avg_ranks = avg_ranks.sort_values("CRPS_avg_rank")
avg_ranks

               RMSE_avg_rank  CRPS_avg_rank
method
mixednormal            2.125          1.625
normal                 1.875          1.750
sample                 3.500          3.125
deterministic          3.500          4.125
crps_ensemble          4.000          4.375

# Table 2: Average Autoregressive results

In [4]:
df_all = pd.read_csv("../results/all_aggregated.csv")

# (display label, experiment name in CSV, dataset key in CSV, factor for RMSE/CRPS/ES)
AR_EXPERIMENTS = [
    ("Burgers'", "Burgers", "1D_Burgers",  1000),
    ("KS",       "KS",      "1D_KS",        100),
    ("T2M",      "T2M",     "WeatherBench",   1),
]

# (display label, experiment override (None -> use outer), method key)
AR_METHODS = [
    (r"$\bm\delta_\theta$",                 None,            "deterministic"),
    (r"$\bm\Sigma_\theta^{\mathrm{diag}}$",  None,            "normal"),
    (r"$\bm\Sigma_\theta^{\mathrm{mix}}$",   None,            "mixednormal"),
    (r"$\bm\Sigma_\theta^{\mathrm{mv}}$",    None,            "mvnormal"),
    (r"$\bm\epsilon_t^\mathrm{ES}$",         None,            "sample"),
    ("iDDPM",                                None,            "iDDPM"),
    ("CRPS-Ens.",                            "crps_ensemble", "crps_ensemble"),
    # ("NDP",                                  "NDP",           "NDP"),
]

# Order in the printed table: RMSE, CRPS, ES
AR_METRICS = [("RMSETest", True), ("CRPSTest", True), ("EnergyScoreTest", True)]


def lookup(exp, ds, method, prefix):
    sel = df_all[(df_all["experiment"] == exp)
                 & (df_all["dataset"] == ds)
                 & (df_all["method"] == method)]
    if sel.empty:
        return np.nan
    return sel.iloc[0][f"{prefix}_mean"]


# Build value matrix [method x (exp, metric)]
rows = [m[0] for m in AR_METHODS]
col_keys = []
data = {}
for disp, exp_name, ds, factor in AR_EXPERIMENTS:
    for prefix, scaled in AR_METRICS:
        key = (disp, prefix)
        col_keys.append(key)
        vals = []
        for _, override, m_key in AR_METHODS:
            e = override if override is not None else exp_name
            v = lookup(e, ds, m_key, prefix)
            if not pd.isna(v) and scaled:
                v = v * factor
            vals.append(v)
        data[key] = vals

values = pd.DataFrame(data, index=rows, columns=pd.MultiIndex.from_tuples(col_keys))

# Average rank (lower = better), NaN cells excluded
ranks = values.rank(axis=0, method="min")
avg_rank = ranks.mean(axis=1)


def fmt_num(x, decimals=2):
    if pd.isna(x):
        return "-"
    return f"{x:.{decimals}f}"


# Determine bold cells (min within each column, by rounded value)
bold = pd.DataFrame(False, index=values.index, columns=values.columns)
for col in values.columns:
    col_vals = values[col].dropna()
    if col_vals.empty:
        continue
    best = round(col_vals.min(), 2)
    for idx, v in col_vals.items():
        if abs(round(v, 2) - best) < 1e-9:
            bold.loc[idx, col] = True

# Bold the best (min) average rank as well
best_rank = round(avg_rank.min(), 2)
bold_rank = {idx: abs(round(r, 2) - best_rank) < 1e-9 for idx, r in avg_rank.items()}


def cell(v, b):
    s = fmt_num(v)
    if b and s != "-":
        return rf"\textbf{{{s}}}"
    return s


lines = []
lines.append(r"\begin{table*}[t]")
lines.append(r"    \small")
lines.append(r"    \centering")
lines.append(r"        \caption{\emph{Autoregressive prediction results}\textemdash{}showing RMSE ($\downarrow$), CRPS ($\downarrow$) and Energy Score (ES, $\downarrow$) only. The RMSE, CRPS, and ES are scaled by the factor 1000 (100) for the Burgers' (KS) equation. Best values per dataset are in bold. A lower average rank indicates better performance.}")
lines.append(r"    \label{tab:autoregressive_results}")
lines.append(r"    \begin{tabular}{lcccccccccc}")
lines.append(r"    \toprule")
lines.append(r"    & \multicolumn{3}{c}{Burgers'}")
lines.append(r"    & \multicolumn{3}{c}{KS}")
lines.append(r"    & \multicolumn{3}{c}{T2M} &\\")
lines.append(r"    \cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}")
lines.append(r"    Model & RMSE & CRPS & ES & RMSE & CRPS & ES & RMSE & CRPS & ES & Avg. Rank \\")
lines.append(r"    \midrule")

for label, _, _ in AR_METHODS:
    cells = []
    for disp, _, _, _ in AR_EXPERIMENTS:
        for prefix, _ in AR_METRICS:
            v = values.loc[label, (disp, prefix)]
            b = bool(bold.loc[label, (disp, prefix)])
            cells.append(cell(v, b))
    r = avg_rank.loc[label]
    r_str = f"{r:.2f}"
    if bold_rank[label]:
        r_str = rf"\textbf{{{r_str}}}"
    cells.append(r_str)
    lines.append(f"    {label} & " + " & ".join(cells) + r" \\")

lines.append(r"    \bottomrule")
lines.append(r"    \end{tabular}")
lines.append(r"\end{table*}")

print("\n".join(lines))

\begin{table*}[t]
    \small
    \centering
        \caption{\emph{Autoregressive prediction results}\textemdash{}showing RMSE ($\downarrow$), CRPS ($\downarrow$) and Energy Score (ES, $\downarrow$) only. The RMSE, CRPS, and ES are scaled by the factor 1000 (100) for the Burgers' (KS) equation. Best values per dataset are in bold. A lower average rank indicates better performance.}
    \label{tab:autoregressive_results}
    \begin{tabular}{lcccccccccc}
    \toprule
    & \multicolumn{3}{c}{Burgers'}
    & \multicolumn{3}{c}{KS}
    & \multicolumn{3}{c}{T2M} &\\
    \cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}
    Model & RMSE & CRPS & ES & RMSE & CRPS & ES & RMSE & CRPS & ES & Avg. Rank \\
    \midrule
    $\bm\delta_\theta$ & 0.95 & 0.16 & 4.26 & 0.56 & 0.24 & 5.93 & 0.76 & 0.39 & 102.50 & 5.11 \\
    $\bm\Sigma_\theta^{\mathrm{diag}}$ & 0.81 & \textbf{0.12} & 3.67 & 0.39 & 0.21 & 5.23 & 0.71 & \textbf{0.35} & 96.49 & 2.56 \\
    $\bm\Sigma_\theta^{\mathrm{mix}}$ & 0.81 & 0.13 & 3.82 & \textbf{0.35} & \textbf{0.20} & \textbf{4.91} & 0.71 & \textbf{0.35} & 95.68 & \textbf{1.67} \\
    $\bm\Sigma_\theta^{\mathrm{mv}}$ & \textbf{0.70} & 0.24 & 6.35 & 0.49 & 0.34 & 7.68 & 0.76 & 0.38 & 101.39 & 5.22 \\
    $\bm\epsilon_t^\mathrm{ES}$ & 0.81 & 0.14 & \textbf{3.59} & 0.59 & 0.34 & 7.34 & - & - & - & 4.33 \\
    iDDPM & 0.83 & 0.15 & 4.68 & 0.50 & \textbf{0.20} & 5.14 & 0.72 & 0.36 & 96.71 & 4.00 \\
    CRPS-Ens. & 1.02 & 0.14 & 4.48 & 0.61 & 0.33 & 7.28 & \textbf{0.69} & 0.36 & \textbf{94.32} & 4.22 \\
    \bottomrule
    \end{tabular}
\end{table*}

# Table 3: Wins/losses against baselines

In [6]:
from scipy.stats import binomtest

df_all = pd.read_csv("../results/all_aggregated.csv")

# 8 UCI datasets (UCI experiment has no mvnormal -> use "normal" as substitute,
# since for UCI mvnormal is equivalent to univariate/normal)
UCI_DATASETS = [
    "concrete", "energy", "kin8nm", "naval-propulsion-plant",
    "power-plant", "protein-tertiary-structure", "wine-quality-red", "yacht",
]

# 3 autoregressive datasets: (experiment, dataset)
AR_DATASETS = [("Burgers", "1D_Burgers"), ("KS", "1D_KS"), ("T2M", "WeatherBench")]

# 5 depth-estimation datasets from external table
# Each entry: (AbsRel, CRPS) for delta, diag, mix, mv, iddpm
DEPTH_DATASETS = {
    "NYUv2":   {"delta": (5.96, 11.32),  "diag": (5.90, 11.32),  "mix": (5.89, 11.35),  "mv": (5.67, 11.02),  "iddpm": (5.81, 11.30)},
    "KITTI":   {"delta": (10.32, 142.92),"diag": (10.07, 138.24),"mix": (9.89, 137.60), "mv": (10.14, 142.28),"iddpm": (10.27, 145.01)},
    "ETH3D":   {"delta": (6.82, 29.23),  "diag": (6.57, 27.89),  "mix": (6.72, 28.66),  "mv": (6.47, 29.43),  "iddpm": (6.51, 31.00)},
    "ScanNet": {"delta": (7.10, 9.19),   "diag": (6.84, 8.86),   "mix": (6.96, 8.99),   "mv": (6.79, 8.85),   "iddpm": (6.94, 9.01)},
    "DIODE":   {"delta": (30.60, 191.39),"diag": (31.52, 196.08),"mix": (31.09, 190.04),"mv": (29.82, 186.63),"iddpm": (30.66, 191.79)},
}

VARIANTS = [
    ("diag", r"$\bm\Sigma_\theta^{\mathrm{diag}}$", "normal"),
    ("mix",  r"$\bm\Sigma_\theta^{\mathrm{mix}}$",  "mixednormal"),
    ("mv",   r"$\bm\Sigma_\theta^{\mathrm{mv}}$",   "mvnormal"),
]


def lookup(exp, ds, method, prefix):
    sel = df_all[(df_all["experiment"] == exp)
                 & (df_all["dataset"] == ds)
                 & (df_all["method"] == method)]
    if sel.empty:
        return np.nan
    return sel.iloc[0][f"{prefix}_mean"]


def collect_pairs(baseline_method, variant_key, variant_method):
    """Return (rmse_pairs, crps_pairs) of (baseline, variant) across all datasets."""
    rmse_pairs, crps_pairs = [], []

    # UCI: 8 datasets. For UCI, mvnormal is equivalent to univariate normal.
    # iDDPM is not available for UCI -> skip UCI for that baseline.
    uci_variant_method = "normal" if variant_method == "mvnormal" else variant_method
    if baseline_method != "iDDPM":
        for ds in UCI_DATASETS:
            if baseline_method == "crps_ensemble":
                b_r = lookup("crps_ensemble", ds, "crps_ensemble", "RMSETest")
                b_c = lookup("crps_ensemble", ds, "crps_ensemble", "CRPSTest")
            else:
                b_r = lookup("UCI", ds, baseline_method, "RMSETest")
                b_c = lookup("UCI", ds, baseline_method, "CRPSTest")
            v_r = lookup("UCI", ds, uci_variant_method, "RMSETest")
            v_c = lookup("UCI", ds, uci_variant_method, "CRPSTest")
            rmse_pairs.append((b_r, v_r))
            crps_pairs.append((b_c, v_c))

    # AR: 3 datasets
    for exp, ds in AR_DATASETS:
        b_exp = "crps_ensemble" if baseline_method == "crps_ensemble" else exp
        b_r = lookup(b_exp, ds, baseline_method, "RMSETest")
        b_c = lookup(b_exp, ds, baseline_method, "CRPSTest")
        v_r = lookup(exp, ds, variant_method, "RMSETest")
        v_c = lookup(exp, ds, variant_method, "CRPSTest")
        rmse_pairs.append((b_r, v_r))
        crps_pairs.append((b_c, v_c))

    # Depth: 5 datasets, available for deterministic and iDDPM baselines.
    if baseline_method in ("deterministic", "iDDPM"):
        depth_key = "delta" if baseline_method == "deterministic" else "iddpm"
        for ds, vals in DEPTH_DATASETS.items():
            b_r, b_c = vals[depth_key]
            v_r, v_c = vals[variant_key]
            rmse_pairs.append((b_r, v_r))
            crps_pairs.append((b_c, v_c))

    return rmse_pairs, crps_pairs


def sign_test(pairs):
    """One-sided sign test: variant wins if variant <= baseline (lower is better).
    Ties favor the variant."""
    wins = 0
    n = 0
    for b, v in pairs:
        if pd.isna(b) or pd.isna(v):
            continue
        n += 1
        if v <= b:
            wins += 1
    if n == 0:
        return 0, 0, np.nan
    p = binomtest(wins, n, 0.5, alternative="greater").pvalue
    return wins, n, p


# Two baseline rows
BASELINES = [
    ("deterministic", r"$\bm\delta_\theta$"),
    ("crps_ensemble", r"CRPS-Ens."),
    ("iDDPM", r"iDDPM"),
]

# Build cell strings: rows = baselines, cols = (metric, variant)
def cell_str(w, n, p):
    if n == 0:
        return "--"
    return f"{w} ({p:.4f})"


lines = []
lines.append(r"\begin{table}[t]")
lines.append(r"    \centering")
lines.append(r"    \small")
lines.append(r"        \caption{Counts of wins compared to each baseline over all our 16 datasets on which we evaluated. In parenthesis the $p$-value of a one-sided sign test. Cells with `--\'{} indicate that the corresponding datasets are not available for that baseline (CRPS-Ens. has no depth-estimation results; iDDPM has no UCI results); the count is then over the remaining datasets.}")
lines.append(r"    \label{tab:sign_test_results}")
lines.append(r"    \begin{tabular}{lcccccc}")
lines.append(r"    \toprule")
lines.append(r"        & \multicolumn{3}{c}{RMSE/AbsRel} & \multicolumn{3}{c}{CRPS} \\")
lines.append(r"        \cmidrule(lr){2-4}\cmidrule(lr){5-7}")
variant_header = " & ".join(v[1] for v in VARIANTS)
lines.append(rf"        Baseline & {variant_header} & {variant_header} \\")
lines.append(r"    \midrule")

for base_method, base_label in BASELINES:
    rmse_cells, crps_cells = [], []
    for v_key, _, v_method in VARIANTS:
        r_pairs, c_pairs = collect_pairs(base_method, v_key, v_method)
        rmse_cells.append(cell_str(*sign_test(r_pairs)))
        crps_cells.append(cell_str(*sign_test(c_pairs)))
    row_cells = rmse_cells + crps_cells
    lines.append(f"        {base_label} & " + " & ".join(row_cells) + r" \\")

lines.append(r"    \bottomrule")
lines.append(r"    \end{tabular}")
lines.append(r"\end{table}")

print("\n".join(lines))

\begin{table}[t]
    \centering
    \small
        \caption{Counts of wins compared to each baseline over all our 16 datasets on which we evaluated. In parenthesis the $p$-value of a one-sided sign test. Cells with `--\'{} indicate that the corresponding datasets are not available for that baseline (CRPS-Ens. has no depth-estimation results; iDDPM has no UCI results); the count is then over the remaining datasets.}
    \label{tab:sign_test_results}
    \begin{tabular}{lcccccc}
    \toprule
        & \multicolumn{3}{c}{RMSE/AbsRel} & \multicolumn{3}{c}{CRPS} \\
        \cmidrule(lr){2-4}\cmidrule(lr){5-7}
        Baseline & $\bm\Sigma_\theta^{\mathrm{diag}}$ & $\bm\Sigma_\theta^{\mathrm{mix}}$ & $\bm\Sigma_\theta^{\mathrm{mv}}$ & $\bm\Sigma_\theta^{\mathrm{diag}}$ & $\bm\Sigma_\theta^{\mathrm{mix}}$ & $\bm\Sigma_\theta^{\mathrm{mv}}$ \\
    \midrule
        $\bm\delta_\theta$ & 15 (0.0003) & 13 (0.0106) & 15 (0.0003) & 15 (0.0003) & 14 (0.0021) & 13 (0.0106) \\
        CRPS-Ens. & 8 (0.1133) & 8 (0.1133) & 8 (0.1133) & 11 (0.0005) & 11 (0.0005) & 8 (0.1133) \\
        iDDPM & 5 (0.3633) & 4 (0.6367) & 7 (0.0352) & 5 (0.3633) & 7 (0.0352) & 5 (0.3633) \\
    \bottomrule
    \end{tabular}
\end{table}

# UCI Tables Full results

In [6]:
df_all = pd.read_csv("../results/all_aggregated.csv")

# Dataset display order and labels
UCI_DATASETS = [
    ("concrete", "Concrete"),
    ("energy", "Energy"),
    ("kin8nm", "Kin8nm"),
    ("naval-propulsion-plant", "Naval"),
    ("power-plant", "Power"),
    ("protein-tertiary-structure", "Protein"),
    ("wine-quality-red", "Wine"),
    ("yacht", "Yacht"),
]

# Method columns: (display label, experiment, method)
METHOD_COLS = [
    (r"$\bm\delta_\theta$",                       "UCI",           "deterministic"),
    (r"$\bm\Sigma_\theta^{\mathrm{diag}}$",        "UCI",           "normal"),
    (r"$\bm\Sigma_\theta^{\mathrm{mix}}$",         "UCI",           "mixednormal"),
    (r"$\bm\epsilon_t^\mathrm{ES}$",               "UCI",           "sample"),
    ("CRPS-Ens.",                                  "crps_ensemble", "crps_ensemble"),
    ("NDP",                                        "NDP",           "NDP"),
]

# Per-dataset scaling for RMSE/CRPS (NLL is not scaled)
UCI_DATASET_FACTOR = {
    "naval-propulsion-plant": 10000,
    "kin8nm": 100,
}


def lookup(experiment, dataset, method, prefix):
    sel = df_all[
        (df_all["experiment"] == experiment)
        & (df_all["dataset"] == dataset)
        & (df_all["method"] == method)
    ]
    if sel.empty:
        return np.nan, np.nan
    row = sel.iloc[0]
    return row[f"{prefix}_mean"], row[f"{prefix}_std"]


def fmt_mean(x):
    if pd.isna(x):
        return "--"
    return f"{x:.2f}"


def fmt_std(x):
    if pd.isna(x):
        return ""
    return format(round(float(x), 2), "g")


def cell_str(mean, std, bold):
    if pd.isna(mean):
        return "--"
    m = fmt_mean(mean)
    s = fmt_std(std)
    if bold:
        m = rf"\textbf{{{m}}}"
    if not s:
        return m
    return f"{m} $\\pm$ {s}"


def build_table(metric_prefix, caption, label, scale=True):
    header = " & " + " & ".join(lbl for lbl, _, _ in METHOD_COLS) + r" \\"
    n_cols = len(METHOD_COLS)
    col_spec = "l|" + "|".join(["c"] * n_cols)

    lines = []
    lines.append(r"\begin{table}[ht]")
    lines.append(r"\centering")
    lines.append(rf"\caption{{{caption}}}")
    lines.append(rf"\label{{{label}}}")
    lines.append(rf"\begin{{tabular}}{{{col_spec}}}")
    lines.append(r"\toprule")
    lines.append(header)
    lines.append(r"\midrule")

    for ds_key, ds_label in UCI_DATASETS:
        factor = UCI_DATASET_FACTOR.get(ds_key, 1) if scale else 1
        means, stds = [], []
        for _, exp, meth in METHOD_COLS:
            m, s = lookup(exp, ds_key, meth, metric_prefix)
            if not pd.isna(m):
                m = m * factor
            if not pd.isna(s):
                s = s * factor
            means.append(m)
            stds.append(s)

        # Bold the best (min) by rounded-2dp value, allowing ties
        finite = [(i, v) for i, v in enumerate(means) if not pd.isna(v)]
        bold_set = set()
        if finite:
            best = min(round(v, 2) for _, v in finite)
            bold_set = {i for i, v in finite if abs(round(v, 2) - best) < 1e-9}

        cells = [cell_str(means[i], stds[i], i in bold_set) for i in range(n_cols)]
        lines.append(f"{ds_label} & " + " & ".join(cells) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines)

In [7]:
print(build_table(
    "RMSETest",
    r"RMSE ($\downarrow$) on the test set for UCI datasets, averaged and with standard deviation.",
    "appendix:add_results:uci_rmse_table",
    scale=True,
))

\begin{table}[ht]
\centering
\caption{RMSE ($\downarrow$) on the test set for UCI datasets, averaged and with standard deviation.}
\label{appendix:add_results:uci_rmse_table}
\begin{tabular}{l|c|c|c|c|c|c}
\toprule
 & $\bm\delta_\theta$ & $\bm\Sigma_\theta^{\mathrm{diag}}$ & $\bm\Sigma_\theta^{\mathrm{mix}}$ & $\bm\epsilon_t^\mathrm{ES}$ & CRPS-Ens. & NDP \\
\midrule
Concrete & 4.82 $\pm$ 0.5 & 4.79 $\pm$ 0.57 & 4.74 $\pm$ 0.52 & 4.83 $\pm$ 0.52 & \textbf{4.60} $\pm$ 0.58 & 9.53 $\pm$ 0.79 \\
Energy & 0.45 $\pm$ 0.06 & 0.45 $\pm$ 0.06 & \textbf{0.44} $\pm$ 0.06 & 0.46 $\pm$ 0.06 & 0.50 $\pm$ 0.07 & -- \\
Kin8nm & 6.91 $\pm$ 0.19 & \textbf{6.88} $\pm$ 0.19 & 6.89 $\pm$ 0.19 & 6.90 $\pm$ 0.19 & 7.95 $\pm$ 0.33 & -- \\
Naval & 1.35 $\pm$ 0.11 & 1.24 $\pm$ 0.1 & \textbf{1.23} $\pm$ 0.08 & 1.24 $\pm$ 0.09 & 7.27 $\pm$ 0.97 & -- \\
Power & 3.86 $\pm$ 0.17 & 3.64 $\pm$ 0.19 & \textbf{3.59} $\pm$ 0.17 & 3.78 $\pm$ 0.17 & 3.63 $\pm$ 0.2 & -- \\
Protein & 3.76 $\pm$ 0.04 & \textbf{3.71} $\pm$ 0.05 & 3.72 $\pm$ 0.05 & 3.76 $\pm$ 0.04 & 3.80 $\pm$ 0.03 & -- \\
Wine & 0.66 $\pm$ 0.07 & \textbf{0.65} $\pm$ 0.06 & 0.68 $\pm$ 0.06 & 0.66 $\pm$ 0.06 & 0.67 $\pm$ 0.05 & -- \\
Yacht & 0.94 $\pm$ 0.61 & \textbf{0.91} $\pm$ 0.57 & 0.95 $\pm$ 0.63 & 0.99 $\pm$ 0.63 & 1.03 $\pm$ 0.5 & -- \\
\bottomrule
\end{tabular}
\end{table}

In [8]:
print(build_table(
    "CRPSTest",
    r"CRPS ($\downarrow$) on the test set for UCI datasets, averaged and with standard deviation.",
    "appendix:add_results:uci_crps_table",
    scale=True,
))

\begin{table}[ht]
\centering
\caption{CRPS ($\downarrow$) on the test set for UCI datasets, averaged and with standard deviation.}
\label{appendix:add_results:uci_crps_table}
\begin{tabular}{l|c|c|c|c|c|c}
\toprule
 & $\bm\delta_\theta$ & $\bm\Sigma_\theta^{\mathrm{diag}}$ & $\bm\Sigma_\theta^{\mathrm{mix}}$ & $\bm\epsilon_t^\mathrm{ES}$ & CRPS-Ens. & NDP \\
\midrule
Concrete & 2.59 $\pm$ 0.3 & 2.47 $\pm$ 0.3 & \textbf{2.43} $\pm$ 0.32 & 2.49 $\pm$ 0.3 & 2.49 $\pm$ 0.33 & 5.38 $\pm$ 0.43 \\
Energy & 0.29 $\pm$ 0.03 & \textbf{0.24} $\pm$ 0.03 & \textbf{0.24} $\pm$ 0.03 & 0.25 $\pm$ 0.03 & 0.28 $\pm$ 0.03 & -- \\
Kin8nm & 3.93 $\pm$ 0.11 & \textbf{3.81} $\pm$ 0.1 & 3.82 $\pm$ 0.1 & 3.83 $\pm$ 0.1 & 4.70 $\pm$ 0.2 & -- \\
Naval & 0.80 $\pm$ 0.09 & 0.55 $\pm$ 0.05 & \textbf{0.54} $\pm$ 0.03 & \textbf{0.54} $\pm$ 0.04 & 4.17 $\pm$ 0.45 & -- \\
Power & 2.04 $\pm$ 0.05 & 1.84 $\pm$ 0.06 & \textbf{1.81} $\pm$ 0.06 & 1.93 $\pm$ 0.07 & 1.92 $\pm$ 0.09 & -- \\
Protein & 1.71 $\pm$ 0.02 & 1.66 $\pm$ 0.03 & \textbf{1.65} $\pm$ 0.03 & 1.69 $\pm$ 0.02 & 1.93 $\pm$ 0.02 & -- \\
Wine & \textbf{0.33} $\pm$ 0.05 & \textbf{0.33} $\pm$ 0.05 & 0.35 $\pm$ 0.05 & \textbf{0.33} $\pm$ 0.05 & 0.39 $\pm$ 0.04 & -- \\
Yacht & 0.41 $\pm$ 0.2 & \textbf{0.35} $\pm$ 0.18 & 0.36 $\pm$ 0.19 & 0.37 $\pm$ 0.2 & 0.48 $\pm$ 0.21 & -- \\
\bottomrule
\end{tabular}
\end{table}

In [9]:
print(build_table(
    "Gaussian NLLTest",
    r"NLL ($\downarrow$) on the test set for UCI datasets, averaged and with standard deviation.",
    "appendix:add_results:uci_nll_table",
    scale=False,
))

\begin{table}[ht]
\centering
\caption{NLL ($\downarrow$) on the test set for UCI datasets, averaged and with standard deviation.}
\label{appendix:add_results:uci_nll_table}
\begin{tabular}{l|c|c|c|c|c|c}
\toprule
 & $\bm\delta_\theta$ & $\bm\Sigma_\theta^{\mathrm{diag}}$ & $\bm\Sigma_\theta^{\mathrm{mix}}$ & $\bm\epsilon_t^\mathrm{ES}$ & CRPS-Ens. & NDP \\
\midrule
Concrete & 10.35 $\pm$ 5.99 & 9.63 $\pm$ 6.52 & 7.90 $\pm$ 4.08 & \textbf{5.00} $\pm$ 1.87 & 6.96 $\pm$ 1.71 & 5.88 $\pm$ 1.62 \\
Energy & 63.59 $\pm$ 85.17 & 1.60 $\pm$ 1.2 & 1.62 $\pm$ 1.28 & 1.63 $\pm$ 1.27 & \textbf{0.80} $\pm$ 0.1 & -- \\
Kin8nm & -0.99 $\pm$ 0.09 & \textbf{-1.22} $\pm$ 0.05 & \textbf{-1.22} $\pm$ 0.04 & \textbf{-1.22} $\pm$ 0.04 & -0.42 $\pm$ 0.16 & -- \\
Naval & 25.47 $\pm$ 26.62 & -7.95 $\pm$ 0.13 & \textbf{-7.99} $\pm$ 0.09 & -7.96 $\pm$ 0.11 & -5.73 $\pm$ 0.08 & -- \\
Power & 2.98 $\pm$ 0.12 & 2.84 $\pm$ 0.19 & 2.92 $\pm$ 0.3 & \textbf{2.77} $\pm$ 0.08 & 2.84 $\pm$ 0.11 & -- \\
Protein & 3.21 $\pm$ 0.36 & 3.19 $\pm$ 0.34 & 3.80 $\pm$ 0.45 & \textbf{2.91} $\pm$ 0.13 & 3.25 $\pm$ 0.03 & -- \\
Wine & 3903.17 $\pm$ 5036.57 & 173.79 $\pm$ 211.5 & 865.12 $\pm$ 880.86 & 116.00 $\pm$ 138.55 & \textbf{58.90} $\pm$ 21.88 & -- \\
Yacht & 55.75 $\pm$ 65.65 & 3.39 $\pm$ 7.32 & 6.34 $\pm$ 13.65 & \textbf{2.58} $\pm$ 4.93 & 2.65 $\pm$ 2.14 & -- \\
\bottomrule
\end{tabular}
\end{table}

## UCI Coverage

In [10]:
UCI_COVERAGE_METHODS = [
    (r"$\bm\delta_\theta$",                       "UCI", "deterministic"),
    (r"$\bm\Sigma_\theta^{\mathrm{diag}}$",        "UCI", "normal"),
    (r"$\bm\Sigma_\theta^{\mathrm{mix}}$",         "UCI", "mixednormal"),
    (r"$\bm\epsilon_t^\mathrm{ES}$",               "UCI", "sample"),
]


def build_coverage_table(metric_prefix, target, caption, label):
    n_cols = len(UCI_COVERAGE_METHODS)
    col_spec = "l|" + "|".join(["c"] * n_cols)
    header = " & " + " & ".join(lbl for lbl, _, _ in UCI_COVERAGE_METHODS) + r" \\"

    lines = []
    lines.append(r"\begin{table}[ht]")
    lines.append(r"\centering")
    lines.append(rf"\caption{{{caption}}}")
    lines.append(rf"\label{{{label}}}")
    lines.append(rf"\begin{{tabular}}{{{col_spec}}}")
    lines.append(r"\toprule")
    lines.append(header)
    lines.append(r"\midrule")

    for ds_key, ds_label in UCI_DATASETS:
        means, stds = [], []
        for _, exp, meth in UCI_COVERAGE_METHODS:
            m, s = lookup(exp, ds_key, meth, metric_prefix)
            means.append(m)
            stds.append(s)

        # Bold the value(s) closest to the target nominal coverage
        finite = [(i, v) for i, v in enumerate(means) if not pd.isna(v)]
        bold_set = set()
        if finite:
            best_dist = min(abs(round(v, 2) - target) for _, v in finite)
            bold_set = {i for i, v in finite
                        if abs(abs(round(v, 2) - target) - best_dist) < 1e-9}

        cells = [cell_str(means[i], stds[i], i in bold_set) for i in range(n_cols)]
        lines.append(f"{ds_label} & " + " & ".join(cells) + r" \\")

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


print(build_coverage_table(
    "C95Test",
    95.0,
    r"95\% coverage on the test set for UCI datasets, averaged and with standard deviation. Bold values are closest to the nominal 95\%.",
    "appendix:add_results:uci_c95_table",
))

\begin{table}[ht]
\centering
\caption{95\% coverage on the test set for UCI datasets, averaged and with standard deviation. Bold values are closest to the nominal 95\%.}
\label{appendix:add_results:uci_c95_table}
\begin{tabular}{l|c|c|c|c}
\toprule
 & $\bm\delta_\theta$ & $\bm\Sigma_\theta^{\mathrm{diag}}$ & $\bm\Sigma_\theta^{\mathrm{mix}}$ & $\bm\epsilon_t^\mathrm{ES}$ \\
\midrule
Concrete & 0.57 $\pm$ 0.05 & 0.68 $\pm$ 0.05 & 0.68 $\pm$ 0.06 & \textbf{0.73} $\pm$ 0.05 \\
Energy & 0.28 $\pm$ 0.12 & \textbf{0.73} $\pm$ 0.06 & 0.72 $\pm$ 0.06 & 0.72 $\pm$ 0.07 \\
Kin8nm & 0.77 $\pm$ 0.02 & \textbf{0.86} $\pm$ 0.02 & \textbf{0.86} $\pm$ 0.01 & \textbf{0.86} $\pm$ 0.01 \\
Naval & 0.24 $\pm$ 0.08 & 0.92 $\pm$ 0.03 & \textbf{0.94} $\pm$ 0.02 & 0.92 $\pm$ 0.03 \\
Power & 0.82 $\pm$ 0.02 & 0.89 $\pm$ 0.01 & 0.87 $\pm$ 0.02 & \textbf{0.90} $\pm$ 0.01 \\
Protein & 0.86 $\pm$ 0.01 & \textbf{0.91} $\pm$ 0 & 0.89 $\pm$ 0.01 & \textbf{0.91} $\pm$ 0.01 \\
Wine & 0.53 $\pm$ 0.12 & 0.76 $\pm$ 0.05 & 0.70 $\pm$ 0.08 & \textbf{0.79} $\pm$ 0.04 \\
Yacht & 0.34 $\pm$ 0.12 & 0.78 $\pm$ 0.09 & 0.78 $\pm$ 0.09 & \textbf{0.79} $\pm$ 0.1 \\
\bottomrule
\end{tabular}
\end{table}

In [11]:
print(build_coverage_table(
    "C90Test",
    90.0,
    r"90\% coverage on the test set for UCI datasets, averaged and with standard deviation. Bold values are closest to the nominal 90\%.",
    "appendix:add_results:uci_c90_table",
))

\begin{table}[ht]
\centering
\caption{90\% coverage on the test set for UCI datasets, averaged and with standard deviation. Bold values are closest to the nominal 90\%.}
\label{appendix:add_results:uci_c90_table}
\begin{tabular}{l|c|c|c|c}
\toprule
 & $\bm\delta_\theta$ & $\bm\Sigma_\theta^{\mathrm{diag}}$ & $\bm\Sigma_\theta^{\mathrm{mix}}$ & $\bm\epsilon_t^\mathrm{ES}$ \\
\midrule
Concrete & 0.51 $\pm$ 0.05 & 0.62 $\pm$ 0.06 & 0.61 $\pm$ 0.07 & \textbf{0.66} $\pm$ 0.05 \\
Energy & 0.24 $\pm$ 0.1 & \textbf{0.64} $\pm$ 0.07 & \textbf{0.64} $\pm$ 0.07 & \textbf{0.64} $\pm$ 0.07 \\
Kin8nm & 0.69 $\pm$ 0.02 & 0.79 $\pm$ 0.02 & \textbf{0.80} $\pm$ 0.02 & 0.79 $\pm$ 0.01 \\
Naval & 0.21 $\pm$ 0.07 & 0.87 $\pm$ 0.04 & \textbf{0.89} $\pm$ 0.03 & 0.88 $\pm$ 0.04 \\
Power & 0.74 $\pm$ 0.02 & 0.83 $\pm$ 0.02 & 0.82 $\pm$ 0.02 & \textbf{0.85} $\pm$ 0.01 \\
Protein & 0.79 $\pm$ 0.01 & \textbf{0.85} $\pm$ 0 & 0.84 $\pm$ 0.01 & \textbf{0.85} $\pm$ 0.02 \\
Wine & 0.45 $\pm$ 0.11 & 0.71 $\pm$ 0.07 & 0.66 $\pm$ 0.09 & \textbf{0.73} $\pm$ 0.05 \\
Yacht & 0.28 $\pm$ 0.1 & 0.73 $\pm$ 0.09 & \textbf{0.74} $\pm$ 0.08 & 0.73 $\pm$ 0.09 \\
\bottomrule
\end{tabular}
\end{table}

In [12]:
print(build_coverage_table(
    "C75Test",
    75.0,
    r"75\% coverage on the test set for UCI datasets, averaged and with standard deviation. Bold values are closest to the nominal 75\%.",
    "appendix:add_results:uci_c75_table",
))

\begin{table}[ht]
\centering
\caption{75\% coverage on the test set for UCI datasets, averaged and with standard deviation. Bold values are closest to the nominal 75\%.}
\label{appendix:add_results:uci_c75_table}
\begin{tabular}{l|c|c|c|c}
\toprule
 & $\bm\delta_\theta$ & $\bm\Sigma_\theta^{\mathrm{diag}}$ & $\bm\Sigma_\theta^{\mathrm{mix}}$ & $\bm\epsilon_t^\mathrm{ES}$ \\
\midrule
Concrete & 0.38 $\pm$ 0.07 & 0.48 $\pm$ 0.05 & 0.48 $\pm$ 0.06 & \textbf{0.52} $\pm$ 0.06 \\
Energy & 0.17 $\pm$ 0.07 & \textbf{0.49} $\pm$ 0.06 & \textbf{0.49} $\pm$ 0.06 & \textbf{0.49} $\pm$ 0.08 \\
Kin8nm & 0.53 $\pm$ 0.03 & \textbf{0.63} $\pm$ 0.03 & \textbf{0.63} $\pm$ 0.02 & \textbf{0.63} $\pm$ 0.01 \\
Naval & 0.16 $\pm$ 0.07 & 0.72 $\pm$ 0.05 & \textbf{0.75} $\pm$ 0.04 & 0.73 $\pm$ 0.05 \\
Power & 0.58 $\pm$ 0.02 & 0.68 $\pm$ 0.02 & 0.67 $\pm$ 0.02 & \textbf{0.69} $\pm$ 0.02 \\
Protein & 0.63 $\pm$ 0.01 & \textbf{0.71} $\pm$ 0.01 & 0.70 $\pm$ 0.01 & 0.70 $\pm$ 0.03 \\
Wine & 0.30 $\pm$ 0.09 & \textbf{0.61} $\pm$ 0.08 & 0.56 $\pm$ 0.11 & 0.57 $\pm$ 0.07 \\
Yacht & 0.20 $\pm$ 0.06 & 0.59 $\pm$ 0.11 & \textbf{0.61} $\pm$ 0.1 & 0.59 $\pm$ 0.09 \\
\bottomrule
\end{tabular}
\end{table}

In [13]:
print(build_coverage_table(
    "C50Test",
    50.0,
    r"50\% coverage on the test set for UCI datasets, averaged and with standard deviation. Bold values are closest to the nominal 50\%.",
    "appendix:add_results:uci_c50_table",
))

\begin{table}[ht]
\centering
\caption{50\% coverage on the test set for UCI datasets, averaged and with standard deviation. Bold values are closest to the nominal 50\%.}
\label{appendix:add_results:uci_c50_table}
\begin{tabular}{l|c|c|c|c}
\toprule
 & $\bm\delta_\theta$ & $\bm\Sigma_\theta^{\mathrm{diag}}$ & $\bm\Sigma_\theta^{\mathrm{mix}}$ & $\bm\epsilon_t^\mathrm{ES}$ \\
\midrule
Concrete & 0.23 $\pm$ 0.05 & 0.30 $\pm$ 0.04 & 0.31 $\pm$ 0.06 & \textbf{0.33} $\pm$ 0.06 \\
Energy & 0.10 $\pm$ 0.05 & 0.30 $\pm$ 0.06 & 0.30 $\pm$ 0.05 & \textbf{0.31} $\pm$ 0.05 \\
Kin8nm & 0.33 $\pm$ 0.02 & \textbf{0.41} $\pm$ 0.03 & 0.40 $\pm$ 0.02 & \textbf{0.41} $\pm$ 0.02 \\
Naval & 0.10 $\pm$ 0.05 & 0.47 $\pm$ 0.04 & \textbf{0.50} $\pm$ 0.04 & \textbf{0.50} $\pm$ 0.05 \\
Power & 0.37 $\pm$ 0.02 & \textbf{0.45} $\pm$ 0.02 & 0.44 $\pm$ 0.02 & \textbf{0.45} $\pm$ 0.01 \\
Protein & 0.40 $\pm$ 0.02 & \textbf{0.47} $\pm$ 0.01 & 0.46 $\pm$ 0.01 & \textbf{0.47} $\pm$ 0.02 \\
Wine & 0.18 $\pm$ 0.06 & \textbf{0.41} $\pm$ 0.09 & 0.37 $\pm$ 0.1 & 0.38 $\pm$ 0.09 \\
Yacht & 0.12 $\pm$ 0.07 & 0.37 $\pm$ 0.11 & \textbf{0.41} $\pm$ 0.11 & 0.37 $\pm$ 0.1 \\
\bottomrule
\end{tabular}
\end{table}

# Full results autoregressive

In [8]:
df_all = pd.read_csv("../results/all_aggregated.csv")

# Experiments: (display label, dataset key, scale factor for RMSE/ES/CRPS, has std)
AR_EXPERIMENTS = [
    (r"\textbf{Burgers'}", "Burgers",       "1D_Burgers",   1000, True),
    (r"\textbf{KS}",       "KS",            "1D_KS",         100, True),
    (r"\textbf{T2M}",      "T2M",           "WeatherBench",    1, False),
]

# Method rows: (display label, experiment_override, method_key)
# experiment_override = None means use the experiment from the outer loop;
# otherwise use the given experiment name.
AR_METHODS = [
    (r"$\bm\delta_\theta$",                       None,            "deterministic"),
    (r"$\bm\Sigma_\theta^{\mathrm{diag}}$",        None,            "normal"),
    (r"$\bm\Sigma_\theta^{\mathrm{mix}}$",         None,            "mixednormal"),
    (r"$\bm\Sigma_\theta^{\mathrm{mv}}$",          None,            "mvnormal"),
    (r"$\bm\epsilon_t^\mathrm{ES}$",               None,            "sample"),
    (r"iDDPM",                                     None,            "iDDPM"),
    (r"CRPS-Ens.",                                 "crps_ensemble", "crps_ensemble"),
    (r"NDP",                                       "NDP",           "NDP"),
]

AR_METRICS = [
    ("RMSETest",          True),   # scaled
    ("EnergyScoreTest",   True),
    ("CRPSTest",          True),
    ("Gaussian NLLTest",  False),  # never scaled
]


def ar_lookup(experiment, dataset, method, prefix):
    sel = df_all[
        (df_all["experiment"] == experiment)
        & (df_all["dataset"] == dataset)
        & (df_all["method"] == method)
    ]
    if sel.empty:
        return np.nan, np.nan
    row = sel.iloc[0]
    return row[f"{prefix}_mean"], row[f"{prefix}_std"]


def fmt_val(x, decimals=2):
    if pd.isna(x):
        return "--"
    return f"{x:.{decimals}f}"


def ar_cell(mean, std, bold, has_std):
    if pd.isna(mean):
        return "--"
    m = fmt_val(mean)
    if bold:
        m = rf"\textbf{{{m}}}"
    if not has_std or pd.isna(std):
        return m
    s = fmt_val(std)
    return rf"\makecell{{{m} \\ ($\pm$ {s})}}"


def build_ar_table():
    n_metrics = len(AR_METRICS)
    col_spec = "|l|l|" + "c" * n_metrics + "|"

    lines = []
    lines.append(r"\begin{table}[ht]")
    lines.append(r"    \centering")
    lines.append(r"        \caption{Full results for the autoregressive prediction tasks. The RMSE, ES, and CRPS are scaled by the factor 1000 (100) for the Burgers' (KS) equation. The standard deviation across the different runs is shown in brackets.}")
    lines.append(r"    \label{tab:full_results_autoregressive}")
    lines.append(rf"    \begin{{tabular}}{{{col_spec}}}")
    lines.append(r"    \toprule")
    lines.append(r"        Experiment & Model & RMSE$\downarrow$ & ES$\downarrow$ & CRPS$\downarrow$ & NLL$\downarrow$ \\")
    lines.append(r"        \midrule")

    for exp_idx, (exp_label, exp_name, ds_name, factor, has_std) in enumerate(AR_EXPERIMENTS):
        # Collect means/stds for every (method, metric) cell
        per_method = []
        for m_label, exp_override, m_key in AR_METHODS:
            exp_for_lookup = exp_override if exp_override is not None else exp_name
            row_means, row_stds = [], []
            for metric_prefix, scaled in AR_METRICS:
                mean, std = ar_lookup(exp_for_lookup, ds_name, m_key, metric_prefix)
                f = factor if scaled else 1
                if not pd.isna(mean):
                    mean = mean * f
                if not pd.isna(std):
                    std = std * f
                row_means.append(mean)
                row_stds.append(std)
            per_method.append((m_label, row_means, row_stds))

        # Bold the best per metric column (min, lower-is-better) using rounded value
        bold_flags = [[False] * n_metrics for _ in per_method]
        for j in range(n_metrics):
            col_vals = [(i, rm[j]) for i, (_, rm, _) in enumerate(per_method) if not pd.isna(rm[j])]
            if not col_vals:
                continue
            best = min(round(v, 2) for _, v in col_vals)
            for i, v in col_vals:
                if abs(round(v, 2) - best) < 1e-9:
                    bold_flags[i][j] = True

        n_rows = len(per_method)
        for i, (m_label, row_means, row_stds) in enumerate(per_method):
            cells = [
                ar_cell(row_means[j], row_stds[j], bold_flags[i][j], has_std)
                for j in range(n_metrics)
            ]
            if i == 0:
                prefix = rf"        \multirow{{{n_rows}}}{{*}}{{{exp_label}}}" + "\n        & "
            else:
                prefix = "        & "
            lines.append(prefix + m_label + " & " + " & ".join(cells) + r" \\")

        if exp_idx < len(AR_EXPERIMENTS) - 1:
            lines.append(r"        \midrule")

    lines.append(r"        \bottomrule")
    lines.append(r"    \end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


print(build_ar_table())

\begin{table}[ht]
    \centering
        \caption{Full results for the autoregressive prediction tasks. The RMSE, ES, and CRPS are scaled by the factor 1000 (100) for the Burgers' (KS) equation. The standard deviation across the different runs is shown in brackets.}
    \label{tab:full_results_autoregressive}
    \begin{tabular}{|l|l|cccc|}
    \toprule
        Experiment & Model & RMSE$\downarrow$ & ES$\downarrow$ & CRPS$\downarrow$ & NLL$\downarrow$ \\
        \midrule
        \multirow{8}{*}{\textbf{Burgers'}}
        & $\bm\delta_\theta$ & \makecell{0.95 \\ ($\pm$ 0.39)} & \makecell{4.26 \\ ($\pm$ 0.71)} & \makecell{0.16 \\ ($\pm$ 0.03)} & \makecell{-7.09 \\ ($\pm$ 0.17)} \\
        & $\bm\Sigma_\theta^{\mathrm{diag}}$ & \makecell{0.81 \\ ($\pm$ 0.27)} & \makecell{3.67 \\ ($\pm$ 0.39)} & \makecell{\textbf{0.12} \\ ($\pm$ 0.02)} & \makecell{-7.12 \\ ($\pm$ 0.09)} \\
        & $\bm\Sigma_\theta^{\mathrm{mix}}$ & \makecell{0.81 \\ ($\pm$ 0.27)} & \makecell{3.82 \\ ($\pm$ 0.39)} & \makecell{0.13 \\ ($\pm$ 0.02)} & \makecell{-6.99 \\ ($\pm$ 0.19)} \\
        & $\bm\Sigma_\theta^{\mathrm{mv}}$ & \makecell{\textbf{0.70} \\ ($\pm$ 0.20)} & \makecell{6.35 \\ ($\pm$ 0.32)} & \makecell{0.24 \\ ($\pm$ 0.02)} & \makecell{-6.10 \\ ($\pm$ 0.04)} \\
        & $\bm\epsilon_t^\mathrm{ES}$ & \makecell{0.81 \\ ($\pm$ 0.49)} & \makecell{\textbf{3.59} \\ ($\pm$ 1.05)} & \makecell{0.14 \\ ($\pm$ 0.03)} & \makecell{-7.00 \\ ($\pm$ 0.14)} \\
        & iDDPM & \makecell{0.83 \\ ($\pm$ 0.26)} & \makecell{4.68 \\ ($\pm$ 1.06)} & \makecell{0.15 \\ ($\pm$ 0.02)} & \makecell{\textbf{-7.21} \\ ($\pm$ 0.07)} \\
        & CRPS-Ens. & \makecell{1.02 \\ ($\pm$ 0.32)} & \makecell{4.48 \\ ($\pm$ 0.47)} & \makecell{0.14 \\ ($\pm$ 0.01)} & \makecell{2.17 \\ ($\pm$ 6.04)} \\
        & NDP & \makecell{4.69 \\ ($\pm$ 2.08)} & \makecell{13.90 \\ ($\pm$ 3.18)} & \makecell{0.43 \\ ($\pm$ 0.08)} & \makecell{-6.20 \\ ($\pm$ 0.28)} \\
        \midrule
        \multirow{8}{*}{\textbf{KS}}
        & $\bm\delta_\theta$ & \makecell{0.56 \\ ($\pm$ 0.06)} & \makecell{5.93 \\ ($\pm$ 0.62)} & \makecell{0.24 \\ ($\pm$ 0.02)} & \makecell{-3.99 \\ ($\pm$ 0.17)} \\
        & $\bm\Sigma_\theta^{\mathrm{diag}}$ & \makecell{0.39 \\ ($\pm$ 0.06)} & \makecell{5.23 \\ ($\pm$ 0.75)} & \makecell{0.21 \\ ($\pm$ 0.03)} & \makecell{-4.04 \\ ($\pm$ 0.14)} \\
        & $\bm\Sigma_\theta^{\mathrm{mix}}$ & \makecell{\textbf{0.35} \\ ($\pm$ 0.04)} & \makecell{\textbf{4.91} \\ ($\pm$ 0.54)} & \makecell{\textbf{0.20} \\ ($\pm$ 0.02)} & \makecell{-4.08 \\ ($\pm$ 0.09)} \\
        & $\bm\Sigma_\theta^{\mathrm{mv}}$ & \makecell{0.49 \\ ($\pm$ 0.01)} & \makecell{7.68 \\ ($\pm$ 0.08)} & \makecell{0.34 \\ ($\pm$ 0.01)} & \makecell{-3.59 \\ ($\pm$ 0.02)} \\
        & $\bm\epsilon_t^\mathrm{ES}$ & \makecell{0.59 \\ ($\pm$ 0.07)} & \makecell{7.34 \\ ($\pm$ 1.51)} & \makecell{0.34 \\ ($\pm$ 0.08)} & \makecell{-3.53 \\ ($\pm$ 0.28)} \\
        & iDDPM & \makecell{0.50 \\ ($\pm$ 0.06)} & \makecell{5.14 \\ ($\pm$ 0.54)} & \makecell{\textbf{0.20} \\ ($\pm$ 0.02)} & \makecell{\textbf{-4.22} \\ ($\pm$ 0.10)} \\
        & CRPS-Ens. & \makecell{0.61 \\ ($\pm$ 0.05)} & \makecell{7.28 \\ ($\pm$ 0.59)} & \makecell{0.33 \\ ($\pm$ 0.03)} & \makecell{-3.48 \\ ($\pm$ 0.07)} \\
        & NDP & \makecell{5.43 \\ ($\pm$ 1.36)} & \makecell{59.24 \\ ($\pm$ 13.84)} & \makecell{2.59 \\ ($\pm$ 0.55)} & \makecell{-1.24 \\ ($\pm$ 0.05)} \\
        \midrule
        \multirow{8}{*}{\textbf{T2M}}
        & $\bm\delta_\theta$ & 0.76 & 102.50 & 0.39 & 1.04 \\
        & $\bm\Sigma_\theta^{\mathrm{diag}}$ & 0.71 & 96.49 & \textbf{0.35} & 0.97 \\
        & $\bm\Sigma_\theta^{\mathrm{mix}}$ & 0.71 & 95.68 & \textbf{0.35} & 0.98 \\
        & $\bm\Sigma_\theta^{\mathrm{mv}}$ & 0.76 & 101.39 & 0.38 & 0.93 \\
        & $\bm\epsilon_t^\mathrm{ES}$ & -- & -- & -- & -- \\
        & iDDPM & 0.72 & 96.71 & 0.36 & \textbf{0.92} \\
        & CRPS-Ens. & \textbf{0.69} & \textbf{94.32} & 0.36 & 1.34 \\
        & NDP & -- & -- & -- & -- \\
        \bottomrule
    \end{tabular}
\end{table}

## Autoregressive coverage

In [13]:
AR_COV_EXPERIMENTS = [
    (r"\textbf{Burgers'}", "Burgers", "1D_Burgers",   True),
    (r"\textbf{KS}",       "KS",      "1D_KS",        True),
    (r"\textbf{T2M}",      "T2M",     "WeatherBench", False),
]

AR_COV_METHODS = [
    (r"$\bm\delta_\theta$",                       None, "deterministic"),
    (r"$\bm\Sigma_\theta^{\mathrm{diag}}$",        None, "normal"),
    (r"$\bm\Sigma_\theta^{\mathrm{mix}}$",         None, "mixednormal"),
    (r"$\bm\Sigma_\theta^{\mathrm{mv}}$",         None, "mvnormal"),
    (r"$\bm\epsilon_t^\mathrm{ES}$",               None, "sample"),
    (r"iDDPM",     None, "iDDPM")
]

AR_COV_METRICS = [
    ("C95Test", 95.0),
    ("C90Test", 90.0),
    ("C75Test", 75.0),
    # ("C50Test", 50.0),
]


def build_ar_coverage_table():
    n_metrics = len(AR_COV_METRICS)
    col_spec = "|l|l|" + "c" * n_metrics + "|"

    lines = []
    lines.append(r"\begin{table}[ht]")
    lines.append(r"    \centering")
    lines.append(r"        \caption{Coverage results for the autoregressive prediction tasks at nominal levels of 95\%, 90\%, 75\% and 50\%. The standard deviation across the different runs is shown in brackets. Bold values are closest to the nominal level per column.}")
    lines.append(r"    \label{tab:coverage_results_autoregressive}")
    lines.append(rf"    \begin{{tabular}}{{{col_spec}}}")
    lines.append(r"    \toprule")
    lines.append(r"        Experiment & Model & C95 & C90 & C75 \\")
    lines.append(r"        \midrule")

    for exp_idx, (exp_label, exp_name, ds_name, has_std) in enumerate(AR_COV_EXPERIMENTS):
        per_method = []
        for m_label, exp_override, m_key in AR_COV_METHODS:
            exp_for_lookup = exp_override if exp_override is not None else exp_name
            row_means, row_stds = [], []
            for metric_prefix, _ in AR_COV_METRICS:
                mean, std = ar_lookup(exp_for_lookup, ds_name, m_key, metric_prefix)
                row_means.append(mean)
                row_stds.append(std)
            per_method.append((m_label, row_means, row_stds))

        # Bold the value closest to nominal target per metric column
        bold_flags = [[False] * n_metrics for _ in per_method]
        for j, (_, target) in enumerate(AR_COV_METRICS):
            col_vals = [(i, rm[j]) for i, (_, rm, _) in enumerate(per_method) if not pd.isna(rm[j])]
            if not col_vals:
                continue
            best_dist = min(abs(round(v, 2) - target) for _, v in col_vals)
            for i, v in col_vals:
                if abs(abs(round(v, 2) - target) - best_dist) < 1e-9:
                    bold_flags[i][j] = True

        n_rows = len(per_method)
        for i, (m_label, row_means, row_stds) in enumerate(per_method):
            cells = [
                ar_cell(row_means[j], row_stds[j], bold_flags[i][j], has_std)
                for j in range(n_metrics)
            ]
            if i == 0:
                prefix = rf"        \multirow{{{n_rows}}}{{*}}{{{exp_label}}}" + "\n        & "
            else:
                prefix = "        & "
            lines.append(prefix + m_label + " & " + " & ".join(cells) + r" \\")

        if exp_idx < len(AR_COV_EXPERIMENTS) - 1:
            lines.append(r"        \midrule")

    lines.append(r"        \bottomrule")
    lines.append(r"    \end{tabular}")
    lines.append(r"\end{table}")
    return "\n".join(lines)


print(build_ar_coverage_table())

\begin{table}[ht]
    \centering
        \caption{Coverage results for the autoregressive prediction tasks at nominal levels of 95\%, 90\%, 75\% and 50\%. The standard deviation across the different runs is shown in brackets. Bold values are closest to the nominal level per column.}
    \label{tab:coverage_results_autoregressive}
    \begin{tabular}{|l|l|ccc|}
    \toprule
        Experiment & Model & C95 & C90 & C75 \\
        \midrule
        \multirow{6}{*}{\textbf{Burgers'}}
        & $\bm\delta_\theta$ & \makecell{0.16 \\ ($\pm$ 0.02)} & \makecell{0.08 \\ ($\pm$ 0.01)} & \makecell{0.01 \\ ($\pm$ 0.01)} \\
        & $\bm\Sigma_\theta^{\mathrm{diag}}$ & \makecell{\textbf{0.96} \\ ($\pm$ 0.01)} & \makecell{\textbf{0.94} \\ ($\pm$ 0.01)} & \makecell{\textbf{0.80} \\ ($\pm$ 0.04)} \\
        & $\bm\Sigma_\theta^{\mathrm{mix}}$ & \makecell{\textbf{0.96} \\ ($\pm$ 0.00)} & \makecell{0.93 \\ ($\pm$ 0.01)} & \makecell{0.76 \\ ($\pm$ 0.10)} \\
        & $\bm\Sigma_\theta^{\mathrm{mv}}$ & \makecell{0.82 \\ ($\pm$ 0.04)} & \makecell{0.75 \\ ($\pm$ 0.05)} & \makecell{0.57 \\ ($\pm$ 0.07)} \\
        & $\bm\epsilon_t^\mathrm{ES}$ & \makecell{0.62 \\ ($\pm$ 0.08)} & \makecell{0.52 \\ ($\pm$ 0.09)} & \makecell{0.30 \\ ($\pm$ 0.10)} \\
        & iDDPM & \makecell{0.12 \\ ($\pm$ 0.03)} & \makecell{0.05 \\ ($\pm$ 0.02)} & \makecell{0.01 \\ ($\pm$ 0.00)} \\
        \midrule
        \multirow{6}{*}{\textbf{KS}}
        & $\bm\delta_\theta$ & \makecell{0.00 \\ ($\pm$ 0.00)} & \makecell{0.00 \\ ($\pm$ 0.00)} & \makecell{0.00 \\ ($\pm$ 0.00)} \\
        & $\bm\Sigma_\theta^{\mathrm{diag}}$ & \makecell{0.96 \\ ($\pm$ 0.00)} & \makecell{0.92 \\ ($\pm$ 0.01)} & \makecell{0.57 \\ ($\pm$ 0.05)} \\
        & $\bm\Sigma_\theta^{\mathrm{mix}}$ & \makecell{\textbf{0.98} \\ ($\pm$ 0.00)} & \makecell{\textbf{0.93} \\ ($\pm$ 0.01)} & \makecell{\textbf{0.63} \\ ($\pm$ 0.04)} \\
        & $\bm\Sigma_\theta^{\mathrm{mv}}$ & \makecell{0.37 \\ ($\pm$ 0.06)} & \makecell{0.20 \\ ($\pm$ 0.04)} & \makecell{0.04 \\ ($\pm$ 0.01)} \\
        & $\bm\epsilon_t^\mathrm{ES}$ & \makecell{0.26 \\ ($\pm$ 0.20)} & \makecell{0.17 \\ ($\pm$ 0.17)} & \makecell{0.05 \\ ($\pm$ 0.08)} \\
        & iDDPM & \makecell{0.00 \\ ($\pm$ 0.00)} & \makecell{0.00 \\ ($\pm$ 0.00)} & \makecell{0.00 \\ ($\pm$ 0.00)} \\
        \midrule
        \multirow{6}{*}{\textbf{T2M}}
        & $\bm\delta_\theta$ & \textbf{0.97} & \textbf{0.95} & \textbf{0.85} \\
        & $\bm\Sigma_\theta^{\mathrm{diag}}$ & 0.84 & 0.77 & 0.61 \\
        & $\bm\Sigma_\theta^{\mathrm{mix}}$ & 0.83 & 0.76 & 0.60 \\
        & $\bm\Sigma_\theta^{\mathrm{mv}}$ & 0.94 & 0.90 & 0.78 \\
        & $\bm\epsilon_t^\mathrm{ES}$ & -- & -- & -- \\
        & iDDPM & 0.85 & 0.78 & 0.62 \\
        \bottomrule
    \end{tabular}
\end{table}

# Runtime

In [11]:
metrics = ['uncertainty_quantification', 'distributional_method', 't_training_avg', 't_training_std']

exp = "Burgers"
path = f"../results/timing/{exp}/" #"../results/Burgers/hparams/mvnormal/"
file_list = ([f for f in glob.iglob(path + "**", recursive = True) if os.path.isfile(f) and f.endswith("csv")])

In [12]:
results = pd.DataFrame()
for file in file_list:
    if os.path.exists(file):
        results_df = pd.read_csv(file, index_col=0)
        results = pd.concat([results, results_df], axis = 1)
rows = metrics.copy()
results = results.loc[rows].T

# results.loc[metrics] = results.loc[metrics].astype("float32")
# results = results.transpose()
# results.index = results[id]
# results.drop(id, axis = 1, inplace = True)
# results.sort_values(ids, inplace = True)
# results.insert(0, "beta",[0.2,0.2,0.35,0.35])
# results["beta"] = [0.2,0.2,0.35,0.35]

In [13]:
results["t_training_avg"] = results["t_training_avg"].astype("float")
results["t_training_std"] = results["t_training_std"].astype("float")

In [14]:
results

,uncertainty_quantification,distributional_method,t_training_avg,t_training_std
0,diffusion,deterministic,7.254869,0.570511
1,diffusion,deterministic,7.265085,0.558380
2,diffusion,deterministic,7.220341,0.616532
3,diffusion,deterministic,6.749123,0.426372
4,diffusion,deterministic,7.530770,0.440645
0,diffusion,normal,6.768328,0.122640
1,diffusion,normal,7.074264,0.557276
2,diffusion,normal,7.939960,0.180733
3,diffusion,normal,7.011914,0.553657
4,diffusion,normal,6.857431,0.326896
0,diffusion,mixednormal,7.853019,0.687857
1,diffusion,mixednormal,8.012485,0.599144
2,diffusion,mixednormal,8.198784,0.754969
3,diffusion,mixednormal,7.068077,0.410891
4,diffusion,mixednormal,7.534120,0.631447
0,diffusion,mvnormal,7.808948,0.789343
1,diffusion,mvnormal,7.996149,0.616209
2,diffusion,mvnormal,8.051381,0.663972
3,diffusion,mvnormal,8.046214,0.483167
4,diffusion,mvnormal,8.138724,0.693329
0,diffusion,sample,10.534243,0.094444
1,diffusion,sample,10.519118,0.087870
2,diffusion,sample,10.467174,0.009467
3,diffusion,sample,10.486968,0.086652
4,diffusion,sample,10.628875,0.210368
0,crps,mvnormal,6.551105,0.109708
1,crps,mvnormal,6.946496,0.310401
2,crps,mvnormal,7.060300,0.111239
3,crps,mvnormal,7.173414,0.160327
4,crps,mvnormal,7.029384,0.229558
0,diffusion,iDDPM,7.473471,0.406593
1,diffusion,iDDPM,7.781042,0.036319
2,diffusion,iDDPM,6.909803,0.410990
3,diffusion,iDDPM,7.540987,0.349563
4,diffusion,iDDPM,7.407146,0.381723

In [15]:
mean = results.groupby(["uncertainty_quantification", "distributional_method"]).mean()
var = results.groupby(["uncertainty_quantification", "distributional_method"]).var()

In [16]:
# Mean of variances
E_s2 = results.groupby("distributional_method")["t_training_std"].apply(lambda s: (s**2).mean())
# Variance of  means
Var_m = var["t_training_avg"]
# Pure mean
final_mean = mean["t_training_avg"]

final_std = np.sqrt(E_s2 + Var_m)

results = pd.DataFrame({
    "final_mean": final_mean,
    "final_std": final_std
}).T

In [17]:
results

uncertainty_quantification      crps     diffusion                        \
distributional_method       mvnormal deterministic     iDDPM mixednormal
final_mean                  6.952140      7.204038  7.422490    7.733297
final_std                   0.540895      0.598947  0.471977    0.769232

uncertainty_quantification
distributional_method       mvnormal    normal     sample
final_mean                  8.008283  7.130379  10.527276
final_std                   0.500743  0.611456   0.132731

In [18]:
# construct table with makecell entries
latex_df = pd.DataFrame(index=[" "])  # single-row table

for col in results.columns:
    mean = results.loc["final_mean", col]
    std  = results.loc["final_std", col]

    latex_df[col] = (
        rf"\makecell{{{mean:.2f} \\ ($\pm$ {std:.2f})}}"
    )

# produce LaTeX table
latex_table = latex_df.to_latex(escape=False)
print(latex_table)

\begin{tabular}{llllllll}
\toprule
 & ('crps', 'mvnormal') & ('diffusion', 'deterministic') & ('diffusion', 'iDDPM') & ('diffusion', 'mixednormal') & ('diffusion', 'mvnormal') & ('diffusion', 'normal') & ('diffusion', 'sample') \\
\midrule
  & \makecell{6.95 \\ ($\pm$ 0.54)} & \makecell{7.20 \\ ($\pm$ 0.60)} & \makecell{7.42 \\ ($\pm$ 0.47)} & \makecell{7.73 \\ ($\pm$ 0.77)} & \makecell{8.01 \\ ($\pm$ 0.50)} & \makecell{7.13 \\ ($\pm$ 0.61)} & \makecell{10.53 \\ ($\pm$ 0.13)} \\
\bottomrule
\end{tabular}